### ISSUE TITLE
When will the support update be made for the arm64 simulator?

### ISSUE THREAD

**Issue by studiogaram** [KakaoAd/kakao-pixel-ios#3]
When will the support update be made for the arm64 simulator?

As a result of checking [the forum article](https://devtalk.kakao.com/t/kakao-ad-ios-sdk-arm64-xcframework/115965), we have found that it will be updated in 2021, but there has been no official release since 2020, so I'm asking you this question.

**Comment by Kim-Deogwon** [comment]
@studiogaram 
4월내에 XCFramework 및 SPM을 지원 할 수 있도록 해보겠습니다.

**Comment by Kim-Deogwon** [comment]
@studiogaram
안녕하세요. 금일 4월11일 해당 기능 지원하여 배포 하였습니다.

**Comment by Jongkeun** [comment]
@studiogaram 혹시 해결되셨나요?
저는 Cocoapods 을 이용해서 0.7.0 version이 설치가 되는데 arm64 용으로 빌드가 안되네요.

@Kim-Deogwon 
`Use of undeclared identifier 'KakaoAdTracker'` 와 같이 나옵니다.
IOS 개발자가 아니라 swift 브릿지 같은 개념은 잘 모르겠지만, objective c에서 swift 코드를 사용 할 수 있도록 하는거 같은데,

<img width="1273" alt="Screenshot 2022-04-20 at 11 58 51 AM" src="https://user-images.githubusercontent.com/33743343/164141461-4364d8fe-9d77-417e-a26a-58e0030ba5e4.png">

이 부분이 삭제 되어도 objective c 예제와 똑같이 사용할 수 있는건가요?

**Comment by Kim-Deogwon** [comment]
@Jongkeun 

안녕하세요. M1 에서 사용하실려면 XCFramework를 사용하셔야 합니다.  XCFramework 직접 임포트하여 사용하시거나, SPM을 이용하시면 됩니다. 

네 테스터 프로젝트로  objective c 및 swift에서 동작되는것을 확인 하였습니다. 
첨부된 테스터의 샘플로 확인 가능하십니다.

**Comment by Jongkeun** [comment]
XCFramework 사용해서 완료했습니다! 
감사합니다!

**Comment by Jongkeun** [comment]
실제 디바이스를 타겟으로 해서 빌드할때는 정상 동작 했는데,
배포하기 위해 any devices 로 두고 빌드하니까 같은 문제가 발생하네요.
M1에서 빌드하기 위해 또 다른 설정이 필요한가요?

**Comment by Kim-Deogwon** [comment]
> 실제 디바이스를 타겟으로 해서 빌드할때는 정상 동작 했는데,
> 배포하기 위해 any devices 로 두고 빌드하니까 같은 문제가 발생하네요.
> M1에서 빌드하기 위해 또 다른 설정이 필요한가요?

빠르게 확인 해보겠습니다.

**Comment by Kim-Deogwon** [comment]
@Jongkeun

안녕하세요. 
M1 디바이스에서 Objective C 샘플 프로젝트로 XCFramework를 임포트 하였습니다. 
임포트 후 AnyDevice 로 아카이빙 해보았으나 관련 에러가 재현되지 않았습니다. 
혹시 XCode 버전 및 테스트 환경이 어떻게 되실까요?

**Comment by Jongkeun** [comment]
> @Jongkeun
> 
> 안녕하세요. M1 디바이스에서 Objective C 샘플 프로젝트로 XCFramework를 임포트 하였습니다. 임포트 후 AnyDevice 로 아카이빙 해보았으나 관련 에러가 재현되지 않았습니다. 혹시 XCode 버전 및 테스트 환경이 어떻게 되실까요?

M1 pro Monterey OS 입니다.
Xcode 버전은 Version 13.3.1 (13E500a) 사용중입니다.
React native 환경에 추가하려고 하고 있습니다.
더 필요하신 부분 있으실까요?

**Comment by Kim-Deogwon** [comment]
@Jongkeun 

안녕하세요. 메일로 연락주신 후 따로 답변이 없으셔서 코멘트 남깁니다. 

금일 배포된 0.7.1 버전 사용시 문제 없을것으로 판단 됩니다. 

감사합니다.

**Comment by Logan-FE** [comment]
Multiple commands produce '~~~/KakaoAdSDK.framework' 가 발생하시진 않나요?

**Comment by Logan-FE** [comment]
Multiple commands produce '~~~~~/KakaoAdSDK.framework' 가 발생하시진 않나요?!

**Comment by Logan-FE** [comment]
@Kim-Deogwon 
> XCFramework 직접 임포트하여 사용하시거나, SPM을 이용하시면 됩니다.


를 이용해서 추가해 보았는데도 
`Use of undeclared identifier 'KakaoAdTracker'`와 같은 이유로
build가 되지 않으면 어떻게 해야할지 알고 싶어요 ㅠ

ReactNative 환경입니다

아래와 같이 하면 해결되네요
1. spm으로 추가
2. AppDelegate.mm / AppDelegate.m에서 import
3. import 시에 #import <KakaoAdSDK/KakaoAdSDK-Swift.h>를 import
4. #import <KakaoAdSDK/KakaoAdSDK.h> 를 하면 계속 "Use of undeclared identifier 'KakaoAdTracker'" 발생
