### ISSUE TITLE
Privacy Manifest와 관련하여 계획이 있을까요?

### ISSUE THREAD

**Issue by dp221125** [KakaoAd/kakao-pixel-ios#4]
### 2024년 05월 01일부터 앱스토어 제출하는 모든 앱들에 대해서 새로운 심사 가이드에 대응해야합니다.
- 심사 가이드 ([링크](https://developer.apple.com/kr/support/third-party-SDK-requirements/))
- 날짜가 확정된 애플 공식 아티클([링크](https://developer.apple.com/news/?id=3d8a9yyh))

이에 따라서 혹시 Privacy Manifest와 관련하여 계획이 있는지 혹은 해당 심사 가이드랑 무관한지 궁금합니다.

**Comment by Kim-Deogwon** [comment]
@dp221125 

안녕하세요. 

Privacy Manifest 적용된 새로운 버전 배포 하였습니다. 

감사합니다.

**Comment by dp221125** [comment]
감사합니다.
