### ISSUE TITLE
PrivacyInfo NSPrivacyTracking 값 관련 

### ISSUE THREAD

**Issue by Daltonicc** [KakaoAd/kakao-pixel-ios#6]
사용 중인 SDK: KaKaoAdSDK(0.7.6)

안녕하세요, 자사 서비스에 KakaoAdSDK를 사용 중인 iOS 개발자입니다.

KaKaoAdSDK(0.7.6)의 현재 버전에 privacy manifest 대응이 된 것으로 알고 있습니다. 그러나 해당 SDK를 사용 중인 앱을 앱스토어에 제출했을 때, 아래와 같은 이슈가 발생하고 있습니다.

<img width="694" alt="스크린샷 2024-05-02 오전 11 36 49" src="https://github.com/KakaoAd/kakao-ad-ios/assets/106509257/bf9fc806-2b4a-4db4-951d-29a36b74889e">

현재 KakaoAdSDK의 PrivayInfo 파일을 살펴보면, NSPrivacyTrackingDomains의 키가 존재하지 않는데도 NSPrivacyTracking값이 true인데요, 트래킹하는 도메인이 없다면 해당 값이 false가 되어야 하지 않나 싶어서 문의 남깁니다.

[https://github.com/KakaoAd/kakao-ad-ios/blob/master/Frameworks/KakaoAdSDK.framework/PrivacyInfo.xcprivacy 4](https://github.com/KakaoAd/kakao-ad-ios/blob/master/Frameworks/KakaoAdSDK.framework/PrivacyInfo.xcprivacy)

감사합니다.

**Comment by Kim-Deogwon** [comment]
@Daltonicc 

안녕하세요.  해당 이슈 수정하여 재배포 하였습니다. 

감사합니다.

**Comment by Daltonicc** [comment]
감사합니다🙇🏿‍♂️

**Comment by Kim-Deogwon** [comment]
@Daltonicc  

이슈가 있어 재배포 하였습니다. CocoaPod 사용중 이시라면 0.7.8 버전으로 사용 부탁 드립니다. 감사합니다.

**Comment by Daltonicc** [comment]
넵 확인했습니다.
